export const LOCALE_COOKIE = "omni-locale";
export const COUNTRY_COOKIE = "omni-country";
export const supportedLocales = ["en", "sk"] as const;
// Legacy type value only: runtime locale selection accepts EN/SK.
export type Locale = (typeof supportedLocales)[number] | "ro";

export function isLocale(value: unknown): value is Locale {
  return typeof value === "string" && supportedLocales.includes(value as (typeof supportedLocales)[number]);
}

export function localeFromCountry(country?: string | null): Locale {
  const code = country?.trim().toUpperCase();
  if (code === "SK") return "sk";
  return "en";
}

export function localeTag(locale: Locale) {
  return locale === "sk" ? "sk-SK" : "en-GB";
}

// Leaderboard membership is decided by a real country code — the viewer's authoritative profile
// country (or the detected country for anonymous visitors) — NOT by the chosen display language.
// Switching language changes copy/branding only; it must never move a player between rankings.
export function leaderboardScope(country?: string | null): "RO" | "SK" | null {
  const code = country?.trim().toUpperCase();
  if (code === "RO") return "RO";
  if (code === "SK") return "SK";
  return null;
}

export const translations = {
  en: {
    brand: "HACKUJ",
    languageName: "English",
    navigation: { challenges: "Challenges", events: "Events", classrooms: "Classrooms", leaderboard: "Leaderboard", dashboard: "Dashboard", team: "My team", schools: "Schools", settings: "Settings" },
    common: { logIn: "Log in", logOut: "Log out", start: "Start learning", rating: "rating", players: "players", teams: "teams", schools: "schools", global: "Global", live: "Live", upcoming: "Upcoming", all: "All", language: "Language", theme: "Theme", light: "Light", dark: "Dark" },
    shell: { label: "LEARN · PRACTICE · COMPETE", engine: "COMPETITION ENGINE", liveEngine: "Live rCTF", mockEngine: "Practice mode", engineDescription: "HACKUJ owns learning and identity. rCTF runs event scoring and isolated challenge instances." },
    challenges: { title: "Solo challenges", label: "PRACTICE · SOLVE · PROGRESS", liveLabel: "LIVE EVENT ENTRY", search: "Search challenges…", empty: "No challenges match these filters." },
    events: { title: "CTF events", label: "SOLO · TEAM · SCHOOL · OPEN", description: "Choose how you want to compete. Your event identity is provisioned securely into rCTF.", mode: "mode", entrants: "entrants", entry: "Entry", openArena: "Open event challenges", createTeam: "Create an eligible team first." },
    classrooms: { title: "Classrooms", label: "TEACH · ASSIGN · REVIEW", intro: "Structured learning spaces for teachers, coaches, and students. Assign challenge sets without mixing classroom progress with live-event scores.", createTitle: "Create a classroom", createDescription: "Open a learning space and receive a private join code.", joinTitle: "Join a classroom", joinDescription: "Use the code shared by your teacher or coach.", name: "Classroom name", create: "Create classroom", code: "Join code", join: "Join classroom", emptyTitle: "No classrooms yet", emptyBody: "Create a classroom for your learners or join one with an invitation code.", teacher: "Teacher", student: "Student", assignments: "assignments", members: "members", loading: "Saving…", codeOnce: "Copy this code now. It is shown only once." },
    leaderboard: { title: "Global leaderboard", localTitle: "Leaderboard", label: "PLAYERS · TEAMS · SCHOOLS", playersTab: "Players", teamsTab: "Teams", schoolsTab: "Schools", globalScope: "Every country", roScope: "Romania", skScope: "Slovakia", explanationGlobal: "The international ranking includes every player, regardless of country.", explanationLocal: "This ranking reflects your country community.", empty: "No ranked participants in this scope yet.", xp: "XP", yourPosition: "Your position", unranked: "Not ranked yet" },
    home: { label: "CYBERSECURITY EDUCATION AND CTF HOSTING", headlineLead: "Learn alone. Build a team.", headlineAccent: "Compete anywhere.", intro: "HACKUJ connects hands-on cybersecurity learning, classrooms, local communities, and live CTF events in one persistent profile.", primary: "Start learning", secondary: "Explore events", proofOne: "Solo challenge tracks", proofTwo: "Teacher-led classrooms", proofThree: "Isolated CTF instances", weekly: "Global leaderboard", nextEvent: "Next team event", enter: "View events", pathsTitle: "One identity across every way you learn", pathsBody: "Practice independently, learn with a classroom, or enter a hosted event without losing your progress.", challengesTitle: "Challenges", challengesBody: "Hands-on web, OSINT, crypto, forensics, and Linux practice.", eventsTitle: "Events", eventsBody: "Solo, team, school, and open CTFs powered by rCTF.", classroomsTitle: "Classrooms", classroomsBody: "Teacher-led assignments and progress separate from event scoring.", leaderboardTitle: "Local and global rankings", leaderboardBody: "Romanian and Slovak communities get local standings; English shows everyone." },
    dashboard: { welcome: "Welcome back", kicker: "PLAYER DASHBOARD", soloProfile: "SOLO PROFILE", cyberRating: "Cyber Rating", level: "LEVEL", lifetimeXp: "LIFETIME XP", dayStreak: "DAY STREAK", nextActions: "Next actions", recommended: "recommended", solveChallenge: "Solve a challenge", solveChallengeBody: "Continue your progression", enterCompetition: "Enter ranked competition", enterCompetitionBody: "Provision an entrant into rCTF", teamPractice: "Team practice", createTeam: "Create a team", teamBody: "Team is an optional identity layer", schoolProfile: "School profile", connectSchool: "Connect a school", schoolBody: "Verification is independent of solo play", recommendedChallenges: "Recommended challenges", viewAll: "View all" },
    onboarding: { kicker: "PLAYER-FIRST ONBOARDING", title: "Build your cyber path.", intro: "Your individual profile comes first. Team and school memberships are optional layers you can add later.", levelQuestion: "What's your current level?", levelBeginner: "I'm starting from zero", levelBasics: "I know the basics", levelCtf: "I already solve CTFs", levelAdvanced: "I'm advanced", levelHint: "We'll adapt the recommended challenge path.", trainQuestion: "What do you want to train?", ethicalHacking: "Ethical Hacking", defensiveSecurity: "Defensive Security", profilePreview: "Profile preview", saving: "Saving…", buildPath: "Build my cyber path", saveError: "Could not save onboarding." },
    team: { kicker: "MY TEAM", independentTeam: "Independent team", teamRating: "Team rating", persistentTitle: "Persistent team layer", persistentBody: "Switch to database mode to create teams, issue hashed join codes and persist membership.", myTeams: "My teams", teamsKicker: "CREATE · JOIN · COMPETE", members: "members", joinCodeEnds: "Current join code ends in …", noTeamTitle: "No team yet", noTeamBody: "Create an independent team or join friends with a code. School affiliation is optional.", actionsTitle: "Team actions", actionsSubtitle: "Create or join independently of a school", createLabel: "Create a team", schoolAffiliation: "School affiliation (optional)", createButton: "Create team", joinLabel: "Join with code", joinButton: "Join team", createError: "Could not create the team.", createSuccess: "Team created. Save this join code now:", joinError: "Could not join the team.", joinSuccess: "You joined the team.", rotateError: "Could not rotate the join code.", newCode: "New join code:", copyNow: "— copy it now.", rotating: "Rotating…", rotate: "Rotate join code" },
    challenge: { pointsUpper: "POINTS", pts: "pts", solves: "solves", difficulty: "Difficulty", objective: "Objective", hint: "Hint", revealHint: "Reveal hint", instanceTitle: "Challenge instance", notStarted: "not started", extend: "Extend", stop: "Stop instance", starting: "Starting…", start: "Start instance", flagSubmission: "FLAG SUBMISSION", capture: "Capture the flag", demoFlag: "Demo flag:", proxiedNote: "Submissions are proxied server-side with the encrypted rCTF entrant token.", submitting: "Submitting…", submitFlag: "Submit flag", backToArena: "Back to Arena", solved: "Solved", gained: "gained", handouts: "Files", connection: "Connection", instanceUnavailable: "Instance unavailable.", engineUnreachable: "Could not reach the competition engine.", actionFailed: "Instance action failed.", noResponse: "No response" },
    entrant: { tba: "TBA", provisioning: "provisioning", provisioned: "provisioned", failed: "failed", pending: "pending", withdrawn: "withdrawn" },
    admin: { section: "Admin", challenges: "Challenges", schools: "School review", events: "Events" },
    event: { back: "All events", scoreboard: "Scoreboard", challenges: "Event challenges", entrants: "entrants", starts: "Starts", ends: "Ends", ended: "Ended", live: "Running now", notStarted: "Not started yet", register: "Register for this event", registered: "You are registered", entryStatus: "Entry", play: "Open", noChallenges: "No challenges have been added to this event yet.", noScoreboard: "No solves yet. Be the first on the board.", rank: "Rank", score: "score", solves: "solves", solvedByYou: "Solved", joinToPlay: "Register to open the event challenges.", teamRequired: "Create an eligible team first.", separateScores: "Event score is separate from your lifetime XP and Cyber Rating.", manage: "Manage event", openInRctf: "Play in rCTF", close: "Close", solvedAlready: "You have already solved this.", locked: "Register for this event to submit flags.", access: "Access", inviteOnly: "Invite only", inviteNeeded: "This event is invite only. Enter the code your organiser gave you.", invitePlaceholder: "EVENT-…", scoredByRctf: "scored by rCTF", scoredByPlatform: "platform scoring", fromRctf: "live rCTF score", standings: "Standings", noHolder: "Nobody is holding the hill yet.", koth: "King of the Hill", divSolo: "Solo", divTeam: "Teams", divSchool: "Schools", firstBlood: "First blood", announcements: "Announcements", history: "Solve history", noSolves: "No solves yet.", export: "Export", solvers: "Solved by", frozen: "The scoreboard is frozen. Solves still count — the full standings are published when the event ends." },
    figure: { label: "FIG. 01 — SYSTEM CROSS-SECTION", title: "What the surface shows. What the system hides.", body: "Every school, network, and service runs on infrastructure nobody sees. Learning to work below that line is the whole discipline.", surface: "SURFACE", below: "INFRASTRUCTURE" },
  },
  sk: {
    brand: "HACKUJ",
    languageName: "Slovenčina",
    navigation: { challenges: "Výzvy", events: "Podujatia", classrooms: "Triedy", leaderboard: "Rebríček", dashboard: "Prehľad", team: "Môj tím", schools: "Školy", settings: "Nastavenia" },
    common: { logIn: "Prihlásiť sa", logOut: "Odhlásiť sa", start: "Začať sa učiť", rating: "rating", players: "hráčov", teams: "tímy", schools: "školy", global: "Globálne", live: "Naživo", upcoming: "Čoskoro", all: "Všetky", language: "Jazyk", theme: "Téma", light: "Svetlý", dark: "Tmavý" },
    shell: { label: "UČ SA · TRÉNUJ · SÚŤAŽ", engine: "SÚŤAŽNÝ ENGINE", liveEngine: "rCTF naživo", mockEngine: "Tréningový režim", engineDescription: "HACKUJ spravuje učenie a identitu. rCTF zabezpečuje skóre a izolované inštancie výziev." },
    challenges: { title: "Samostatné výzvy", label: "TRÉNUJ · RIEŠ · NAPREDUJ", liveLabel: "VSTUP DO ŽIVÉHO PODUJATIA", search: "Hľadať výzvy…", empty: "Týmto filtrom nezodpovedajú žiadne výzvy." },
    events: { title: "CTF podujatia", label: "SOLO · TÍM · ŠKOLA · OPEN", description: "Vyber si, ako chceš súťažiť. Tvoja identita pre podujatie sa bezpečne vytvorí v rCTF.", mode: "režim", entrants: "účastníkov", entry: "Vstup", openArena: "Otvoriť výzvy podujatia", createTeam: "Najprv vytvor oprávnený tím." },
    classrooms: { title: "Triedy", label: "UČ · ZADÁVAJ · SLEDUJ", intro: "Vzdelávacie priestory pre učiteľov, trénerov a študentov. Pokrok v triede zostáva oddelený od skóre živých podujatí.", createTitle: "Vytvoriť triedu", createDescription: "Otvor vzdelávací priestor a získaj súkromný kód.", joinTitle: "Pridať sa do triedy", joinDescription: "Použi kód od učiteľa alebo trénera.", name: "Názov triedy", create: "Vytvoriť triedu", code: "Vstupný kód", join: "Pridať sa", emptyTitle: "Zatiaľ nemáš žiadne triedy", emptyBody: "Vytvor triedu pre študentov alebo sa pridaj pomocou pozvánky.", teacher: "Učiteľ", student: "Študent", assignments: "úloh", members: "členov", loading: "Ukladá sa…", codeOnce: "Skopíruj kód teraz. Zobrazí sa iba raz." },
    leaderboard: { title: "Rebríček Slovensko", localTitle: "Rebríček", label: "HRÁČI · TÍMY · ŠKOLY", playersTab: "Hráči", teamsTab: "Tímy", schoolsTab: "Školy", globalScope: "Všetky krajiny", roScope: "Rumunsko", skScope: "Slovensko", explanationGlobal: "Medzinárodný rebríček zahŕňa všetkých hráčov.", explanationLocal: "Tento rebríček zobrazuje komunitu zo Slovenska.", empty: "V tejto skupine zatiaľ nie sú hodnotení účastníci.", xp: "XP", yourPosition: "Tvoja pozícia", unranked: "Zatiaľ bez umiestnenia" },
    home: { label: "VZDELÁVANIE V KYBERBEZPEČNOSTI A CTF", headlineLead: "Trénuj sám. Zostav tím.", headlineAccent: "Súťaž kdekoľvek.", intro: "HACKUJ spája praktické učenie, triedy, miestnu komunitu a živé CTF podujatia v jednom trvalom profile.", primary: "Začať sa učiť", secondary: "Pozrieť podujatia", proofOne: "Samostatné tréningové cesty", proofTwo: "Triedy vedené učiteľmi", proofThree: "Izolované CTF inštancie", weekly: "Rebríček Slovensko", nextEvent: "Najbližšie tímové podujatie", enter: "Pozrieť podujatia", pathsTitle: "Jedna identita pre každý spôsob učenia", pathsBody: "Trénuj samostatne, uč sa v triede alebo vstúp do podujatia bez straty pokroku.", challengesTitle: "Výzvy", challengesBody: "Praktické úlohy z webu, OSINT, kryptografie, forenznej analýzy a Linuxu.", eventsTitle: "Podujatia", eventsBody: "Solo, tímové, školské a open CTF podujatia cez rCTF.", classroomsTitle: "Triedy", classroomsBody: "Úlohy a vzdelávací pokrok oddelené od súťažného skóre.", leaderboardTitle: "Miestne a globálne rebríčky", leaderboardBody: "Slovenská a rumunská komunita má miestne poradie; angličtina zobrazuje všetkých." },
    dashboard: { welcome: "Vitaj späť", kicker: "PREHĽAD HRÁČA", soloProfile: "SÓLO PROFIL", cyberRating: "Cyber Rating", level: "ÚROVEŇ", lifetimeXp: "CELKOVÉ XP", dayStreak: "DNI V RADE", nextActions: "Ďalšie kroky", recommended: "odporúčané", solveChallenge: "Vyrieš výzvu", solveChallengeBody: "Pokračuj v napredovaní", enterCompetition: "Vstúp do súťaže", enterCompetitionBody: "Priprav účastníka v rCTF", teamPractice: "Tímový tréning", createTeam: "Vytvor tím", teamBody: "Tím je voliteľná vrstva identity", schoolProfile: "Školský profil", connectSchool: "Pripoj školu", schoolBody: "Overenie je nezávislé od sólo hry", recommendedChallenges: "Odporúčané výzvy", viewAll: "Zobraziť všetky" },
    onboarding: { kicker: "NASTAVENIE HRÁČA", title: "Vytvor si svoju kyber cestu.", intro: "Tvoj individuálny profil je na prvom mieste. Členstvo v tíme a škole sú voliteľné vrstvy, ktoré môžeš pridať neskôr.", levelQuestion: "Aká je tvoja aktuálna úroveň?", levelBeginner: "Začínam od nuly", levelBasics: "Poznám základy", levelCtf: "Už riešim CTF", levelAdvanced: "Som pokročilý", levelHint: "Prispôsobíme odporúčanú cestu výziev.", trainQuestion: "Čo chceš trénovať?", ethicalHacking: "Etický hacking", defensiveSecurity: "Obranná bezpečnosť", profilePreview: "Náhľad profilu", saving: "Ukladá sa…", buildPath: "Vytvoriť moju cestu", saveError: "Nastavenie sa nepodarilo uložiť." },
    team: { kicker: "MÔJ TÍM", independentTeam: "Nezávislý tím", teamRating: "Rating tímu", persistentTitle: "Trvalá tímová vrstva", persistentBody: "Prepni do databázového režimu, aby si mohol vytvárať tímy, generovať prístupové kódy a uchovávať členstvo.", myTeams: "Moje tímy", teamsKicker: "VYTVOR · PRIDAJ SA · SÚŤAŽ", members: "členov", joinCodeEnds: "Aktuálny prístupový kód končí na …", noTeamTitle: "Zatiaľ žiadny tím", noTeamBody: "Vytvor nezávislý tím alebo sa pripoj k priateľom pomocou kódu. Príslušnosť k škole je voliteľná.", actionsTitle: "Tímové akcie", actionsSubtitle: "Vytvor tím alebo sa pridaj nezávisle od školy", createLabel: "Vytvor tím", schoolAffiliation: "Príslušnosť k škole (voliteľné)", createButton: "Vytvoriť tím", joinLabel: "Pridaj sa pomocou kódu", joinButton: "Pridať sa do tímu", createError: "Tím sa nepodarilo vytvoriť.", createSuccess: "Tím vytvorený. Ulož si teraz tento prístupový kód:", joinError: "Nepodarilo sa pripojiť k tímu.", joinSuccess: "Pripojil si sa k tímu.", rotateError: "Kód sa nepodarilo obnoviť.", newCode: "Nový prístupový kód:", copyNow: "— skopíruj ho teraz.", rotating: "Obnovuje sa…", rotate: "Obnoviť prístupový kód" },
    challenge: { pointsUpper: "BODOV", pts: "b.", solves: "vyriešení", difficulty: "Náročnosť", objective: "Cieľ", hint: "Nápoveda", revealHint: "Zobraziť nápovedu", instanceTitle: "Inštancia výzvy", notStarted: "nespustená", extend: "Predĺžiť", stop: "Zastaviť inštanciu", starting: "Spúšťa sa…", start: "Spustiť inštanciu", flagSubmission: "ODOSLANIE FLAGU", capture: "Získaj flag", demoFlag: "Demo flag:", proxiedNote: "Odoslania sa spracúvajú na serveri pomocou šifrovaného rCTF tokenu účastníka.", submitting: "Odosiela sa…", submitFlag: "Odoslať flag", backToArena: "Späť na výzvy", solved: "Vyriešené", gained: "získané", handouts: "Súbory", connection: "Pripojenie", instanceUnavailable: "Inštancia nie je dostupná.", engineUnreachable: "Nepodarilo sa spojiť so súťažným enginom.", actionFailed: "Akcia s inštanciou zlyhala.", noResponse: "Žiadna odpoveď" },
    entrant: { tba: "Čoskoro", provisioning: "pripravuje sa", provisioned: "pripravené", failed: "zlyhalo", pending: "čaká", withdrawn: "stiahnuté" },
    admin: { section: "Správa", challenges: "Výzvy", schools: "Overenie škôl", events: "Podujatia" },
    event: { back: "Všetky podujatia", scoreboard: "Rebríček", challenges: "Výzvy podujatia", entrants: "účastníkov", starts: "Začína", ends: "Končí", ended: "Ukončené", live: "Prebieha", notStarted: "Zatiaľ nezačalo", register: "Prihlásiť sa na podujatie", registered: "Si prihlásený", entryStatus: "Prihláška", play: "Otvoriť", noChallenges: "Do tohto podujatia zatiaľ neboli pridané žiadne výzvy.", noScoreboard: "Zatiaľ žiadne vyriešenia. Buď prvý v rebríčku.", rank: "Poradie", score: "skóre", solves: "vyriešení", solvedByYou: "Vyriešené", joinToPlay: "Prihlás sa, aby si otvoril výzvy podujatia.", teamRequired: "Najprv vytvor oprávnený tím.", separateScores: "Skóre podujatia je oddelené od tvojho XP a Cyber Ratingu.", manage: "Spravovať podujatie", openInRctf: "Hrať v rCTF", close: "Zavrieť", solvedAlready: "Túto výzvu si už vyriešil.", locked: "Prihlás sa na podujatie, aby si mohol odosielať flagy.", access: "Prístup", inviteOnly: "Len na pozvánku", inviteNeeded: "Toto podujatie je len na pozvánku. Zadaj kód od organizátora.", invitePlaceholder: "EVENT-…", scoredByRctf: "hodnotí rCTF", scoredByPlatform: "interné hodnotenie", fromRctf: "živé skóre rCTF", standings: "Priebežné poradie", noHolder: "Kopec zatiaľ nikto nedrží.", koth: "King of the Hill", divSolo: "Jednotlivci", divTeam: "Tímy", divSchool: "Školy", firstBlood: "Prvá krv", announcements: "Oznamy", history: "História riešení", noSolves: "Zatiaľ žiadne vyriešenia.", export: "Export", solvers: "Vyriešili", frozen: "Rebríček je zmrazený. Vyriešenia stále platia — úplné poradie sa zverejní po skončení podujatia." },
    figure: { label: "OBR. 01 — REZ SYSTÉMOM", title: "Čo ukazuje povrch. Čo systém skrýva.", body: "Každá škola, sieť a služba beží na infraštruktúre, ktorú nikto nevidí. Naučiť sa pracovať pod touto čiarou je podstatou celého odboru.", surface: "POVRCH", below: "INFRAŠTRUKTÚRA" },
  },
} as const;

export function getDictionary(locale: Locale) {
  return translations[locale === "ro" ? "en" : locale];
}
